export type UserRole = 'student' | 'driver' | 'admin';

export interface CollegeInfo {
  id: string;
    name: string;
      shortName: string;
        districtId: string;
          category: 'Engineering & Tech' | 'Arts & Science' | 'Medical & Allied' | 'University & Research' | 'Polytechnic';
            address: string;
              contactPhone?: string;
                popularBusRoutes?: string[];
                }

                export interface UserAccount {
                  id: string;
                    name: string;
                      role: UserRole;
                        email: string;
                          avatar?: string;
                            studentId?: string; // For parent/student
                              busId?: string;     // For driver or student
                                phone?: string;
                                  department?: string;
                                    rollNumber?: string;
                                      collegeName?: string;
                                        districtId?: string;
                                          campusAddress?: string;
                                            parentName?: string;
                                              parentPhone?: string;
                                                year?: string;
                                                  designation?: string;
                                                    employeeId?: string;
                                                      isTransportManager?: boolean;
                                                        officialEmail?: string;
                                                          handoverDate?: string;
                                                            previousManagerName?: string;
                                                              password?: string;
                                                                accessTag?: string; // e.g. 'Student / Parent Access'
                                                                  userType?: 'student' | 'parent';
                                                                    isParent?: boolean;
                                                                    }

                                                                    export type BusStatus = 'on-route' | 'idle' | 'maintenance' | 'special-trip';

                                                                    export interface DistrictConfig {
                                                                      id: string;
                                                                        name: string;
                                                                          state: string;
                                                                            code: string; // e.g. "TIN" / "TN-72"
                                                                              center: [number, number]; // [lat, lng]
                                                                                zoom: number;
                                                                                  campusName: string;
                                                                                    campusAddress: string;
                                                                                      campusLocation: { lat: number; lng: number; name?: string; address?: string };
                                                                                        popularLandmarks: string[];
                                                                                          tagline: string;
                                                                                          }

                                                                                          export interface DriverInfo {
                                                                                            id: string;
                                                                                              name: string;
                                                                                                phone: string;
                                                                                                  licenseNumber: string;
                                                                                                    experienceYears: number;
                                                                                                      photoUrl?: string;
                                                                                                        rating: number;
                                                                                                        }

                                                                                                        export interface Bus {
                                                                                                          id: string;
                                                                                                            busNumber: string;
                                                                                                              plateNumber: string;
                                                                                                                model: string;
                                                                                                                  capacity: number;
                                                                                                                    currentPassengers: number;
                                                                                                                      status: BusStatus;
                                                                                                                        driverId: string;
                                                                                                                          driverName: string;
                                                                                                                            driverPhone: string;
                                                                                                                              assignedRouteId?: string;
                                                                                                                                districtId?: string;
                                                                                                                                  currentOdometer: number;
                                                                                                                                    fuelTankCapacity: number; // in Liters
                                                                                                                                      currentFuelLevel: number; // in Liters
                                                                                                                                        fuelEfficiencyKmpl: number; // calculated historical average
                                                                                                                                          expectedEfficiencyKmpl: number; // benchmark e.g., 4.5 km/l
                                                                                                                                            fuelType: 'Diesel' | 'EV' | 'CNG';
                                                                                                                                              year: number;
                                                                                                                                                lastServiceDate: string;
                                                                                                                                                }

                                                                                                                                                export interface Stop {
                                                                                                                                                  id: string;
                                                                                                                                                    routeId: string;
                                                                                                                                                      name: string;
                                                                                                                                                        sequence: number;
                                                                                                                                                          lat: number;
                                                                                                                                                            lng: number;
                                                                                                                                                              scheduledTime: string; // e.g. "07:35 AM"
                                                                                                                                                                estimatedArrival?: string;
                                                                                                                                                                  dwellTimeMin: number;
                                                                                                                                                                    studentsRegistered: number;
                                                                                                                                                                      isCompleted?: boolean;
                                                                                                                                                                      }

                                                                                                                                                                      export interface Route {
                                                                                                                                                                        id: string;
                                                                                                                                                                          code: string; // e.g. "R-04"
                                                                                                                                                                            name: string;
                                                                                                                                                                              shift: 'Morning Pickup' | 'Evening Drop' | 'Midday Transit' | 'Special Excursion';
                                                                                                                                                                                color: string;
                                                                                                                                                                                  totalDistanceKm: number;
                                                                                                                                                                                    estimatedDurationMin: number;
                                                                                                                                                                                      assignedBusId?: string;
                                                                                                                                                                                        districtId?: string;
                                                                                                                                                                                          status: 'active' | 'scheduled' | 'completed' | 'standby';
                                                                                                                                                                                            stops: Stop[];
                                                                                                                                                                                              pathCoordinates: [number, number][]; // Polyline coords [lat, lng]
                                                                                                                                                                                              }

                                                                                                                                                                                              export interface StudentPassenger {
                                                                                                                                                                                                id: string;
                                                                                                                                                                                                  name: string;
                                                                                                                                                                                                    rollNumber: string;
                                                                                                                                                                                                      department: string;
                                                                                                                                                                                                        year: string;
                                                                                                                                                                                                          districtId?: string;
                                                                                                                                                                                                            busId: string;
                                                                                                                                                                                                              busNumber: string;
                                                                                                                                                                                                                routeId: string;
                                                                                                                                                                                                                  stopId: string;
                                                                                                                                                                                                                    stopName: string;
                                                                                                                                                                                                                      parentName: string;
                                                                                                                                                                                                                        parentPhone: string;
                                                                                                                                                                                                                          parentEmail?: string;
                                                                                                                                                                                                                            status: 'waiting-at-stop' | 'boarded' | 'arrived-campus' | 'absent';
                                                                                                                                                                                                                              boardedAtTime?: string;
                                                                                                                                                                                                                                arrivedAtTime?: string;
                                                                                                                                                                                                                                  avatar?: string;
                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                  export interface TripEndReport {
                                                                                                                                                                                                                                    busId: string;
                                                                                                                                                                                                                                      routeId: string;
                                                                                                                                                                                                                                        driverId: string;
                                                                                                                                                                                                                                          driverName: string;
                                                                                                                                                                                                                                            totalDistanceKm: number;
                                                                                                                                                                                                                                              endingOdometer: number;
                                                                                                                                                                                                                                                fuelRefilled: boolean;
                                                                                                                                                                                                                                                  fuelLiters?: number;
                                                                                                                                                                                                                                                    fuelCostPerLiter?: number;
                                                                                                                                                                                                                                                      fuelStationName?: string;
                                                                                                                                                                                                                                                        receiptNumber?: string;
                                                                                                                                                                                                                                                          totalDelayMinutes: number;
                                                                                                                                                                                                                                                            delayReason?: string;
                                                                                                                                                                                                                                                              studentsBoardedCount: number;
                                                                                                                                                                                                                                                                notes?: string;
                                                                                                                                                                                                                                                                  completedAt: string;
                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                  export interface LiveLocation {
                                                                                                                                                                                                                                                                    busId: string;
                                                                                                                                                                                                                                                                      busNumber: string;
                                                                                                                                                                                                                                                                        routeId?: string;
                                                                                                                                                                                                                                                                          lat: number;
                                                                                                                                                                                                                                                                            lng: number;
                                                                                                                                                                                                                                                                              speedKmph: number;
                                                                                                                                                                                                                                                                                headingDeg: number;
                                                                                                                                                                                                                                                                                  timestamp: string;
                                                                                                                                                                                                                                                                                    currentStopIndex: number;
                                                                                                                                                                                                                                                                                      nextStopName: string;
                                                                                                                                                                                                                                                                                        etaNextStopMin: number;
                                                                                                                                                                                                                                                                                          distanceToNextStopKm: number;
                                                                                                                                                                                                                                                                                            delayMinutes: number;
                                                                                                                                                                                                                                                                                              isOffRoute: boolean;
                                                                                                                                                                                                                                                                                                offRouteDistanceMeters: number;
                                                                                                                                                                                                                                                                                                  ignitionStatus: 'ON' | 'IDLE' | 'OFF';
                                                                                                                                                                                                                                                                                                    driverStatusMessage?: string;
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                    export interface FuelLog {
                                                                                                                                                                                                                                                                                                      id: string;
                                                                                                                                                                                                                                                                                                        busId: string;
                                                                                                                                                                                                                                                                                                          busNumber: string;
                                                                                                                                                                                                                                                                                                            date: string;
                                                                                                                                                                                                                                                                                                              time: string;
                                                                                                                                                                                                                                                                                                                litersFilled: number;
                                                                                                                                                                                                                                                                                                                  costPerLiter: number;
                                                                                                                                                                                                                                                                                                                    totalCost: number;
                                                                                                                                                                                                                                                                                                                      odometerReading: number;
                                                                                                                                                                                                                                                                                                                        previousOdometerReading: number;
                                                                                                                                                                                                                                                                                                                          distanceTravelledKm: number;
                                                                                                                                                                                                                                                                                                                            calculatedMileageKmpl: number;
                                                                                                                                                                                                                                                                                                                              expectedMileageKmpl: number;
                                                                                                                                                                                                                                                                                                                                deviationPercent: number; // negative means drop in mileage
                                                                                                                                                                                                                                                                                                                                  fuelStationName: string;
                                                                                                                                                                                                                                                                                                                                    receiptNumber: string;
                                                                                                                                                                                                                                                                                                                                      driverName: string;
                                                                                                                                                                                                                                                                                                                                        isAnomaly: boolean;
                                                                                                                                                                                                                                                                                                                                          anomalyReason?: string;
                                                                                                                                                                                                                                                                                                                                            notes?: string;
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                            export interface FuelAnomalyAlert {
                                                                                                                                                                                                                                                                                                                                              id: string;
                                                                                                                                                                                                                                                                                                                                                busId: string;
                                                                                                                                                                                                                                                                                                                                                  busNumber: string;
                                                                                                                                                                                                                                                                                                                                                    date: string;
                                                                                                                                                                                                                                                                                                                                                      severity: 'high' | 'medium' | 'low';
                                                                                                                                                                                                                                                                                                                                                        title: string;
                                                                                                                                                                                                                                                                                                                                                          description: string;
                                                                                                                                                                                                                                                                                                                                                            calculatedMileage: number;
                                                                                                                                                                                                                                                                                                                                                              expectedMileage: number;
                                                                                                                                                                                                                                                                                                                                                                dropPercent: number;
                                                                                                                                                                                                                                                                                                                                                                  estimatedFuelLossLiters: number;
                                                                                                                                                                                                                                                                                                                                                                    status: 'open' | 'investigating' | 'resolved';
                                                                                                                                                                                                                                                                                                                                                                      resolvedNote?: string;
                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                      export interface SpecialTrip {
                                                                                                                                                                                                                                                                                                                                                                        id: string;
                                                                                                                                                                                                                                                                                                                                                                          tripName: string;
                                                                                                                                                                                                                                                                                                                                                                            purpose: 'Industrial Visit' | 'Sports Meet' | 'Cultural Fest' | 'Academic Conference' | 'Special Event';
                                                                                                                                                                                                                                                                                                                                                                              department: string;
                                                                                                                                                                                                                                                                                                                                                                                venueName: string;
                                                                                                                                                                                                                                                                                                                                                                                  venueAddress: string;
                                                                                                                                                                                                                                                                                                                                                                                    venueLat: number;
                                                                                                                                                                                                                                                                                                                                                                                      venueLng: number;
                                                                                                                                                                                                                                                                                                                                                                                        districtId?: string;
                                                                                                                                                                                                                                                                                                                                                                                          startDateTime: string;
                                                                                                                                                                                                                                                                                                                                                                                            endDateTime: string;
                                                                                                                                                                                                                                                                                                                                                                                              passengerCount: number;
                                                                                                                                                                                                                                                                                                                                                                                                assignedBusId: string;
                                                                                                                                                                                                                                                                                                                                                                                                  assignedBusNumber: string;
                                                                                                                                                                                                                                                                                                                                                                                                    driverId: string;
                                                                                                                                                                                                                                                                                                                                                                                                      driverName: string;
                                                                                                                                                                                                                                                                                                                                                                                                        driverPhone: string;
                                                                                                                                                                                                                                                                                                                                                                                                          contactPerson: string;
                                                                                                                                                                                                                                                                                                                                                                                                            contactPhone: string;
                                                                                                                                                                                                                                                                                                                                                                                                              status: 'scheduled' | 'in-progress' | 'completed' | 'cancelled';
                                                                                                                                                                                                                                                                                                                                                                                                                notes?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                  estimatedDistanceKm: number;
                                                                                                                                                                                                                                                                                                                                                                                                                    budgetAllocated: number;
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                    export interface FleetAlert {
                                                                                                                                                                                                                                                                                                                                                                                                                      id: string;
                                                                                                                                                                                                                                                                                                                                                                                                                        type: 'delay' | 'off-route' | 'fuel-anomaly' | 'speeding' | 'stop-arrival' | 'special-trip';
                                                                                                                                                                                                                                                                                                                                                                                                                          busId?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                            busNumber?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                              title: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                message: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                  timestamp: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                    severity: 'info' | 'warning' | 'critical';
                                                                                                                                                                                                                                                                                                                                                                                                                                      isRead: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                      export interface AttendanceRecord {
                                                                                                                                                                                                                                                                                                                                                                                                                                        id: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                          studentId: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                            studentName: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                              rollNumber: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                busId: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  tripId: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    date: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      scanTime: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        seatNumber: number;
                                                                                                                                                                                                                                                                                                                                                                                                                                                          status: 'present';
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                          export interface SeatAssignment {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            id: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              busId: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                tripId: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  seatNumber: number;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    studentId: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      studentName: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rollNumber: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          assignedAt: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }